import os
import re
from weasyprint import HTML, CSS

# ----------------------------------------------------
# 1. SETUP FILE LIST & PATHS
# ----------------------------------------------------
files = [
    # 1. Title Page (Inner Cover)
    "Title-Page.html",
    # 2. Certificate
    "Certificate.html",
    # 3. Acknowledgment
    "Acknowledgment.html",
    # 4. Table of Contents
    "Table-of-Contents.html",
    # 5. Chapters
    "Chapter-1-Introduction.html",
    "Chapter-2-Literature-Survey.html",
    "Chapter-3-Scope-of-Project.html",
    "Chapter-4-Methodology.html",
    "Chapter-5-Design-Details.html",
    "Chapter-6-Results-and-Applications.html",
    "Chapter-7-Conclusion.html",
    "References.html"
]

base_dir = "project-report"
output_pdf = os.path.join(base_dir, "Attendro_Final_Report.pdf")

# ----------------------------------------------------
# 2. DEFINE STRICT CSS RULES (User Requirements)
# ----------------------------------------------------
css_string = """
@page {
    size: A4;
    margin-top: 2.5cm;
    margin-bottom: 1.25cm;
    margin-left: 3.5cm;
    margin-right: 1.25cm;
    @bottom-center {
        content: counter(page);
        font-family: "Times New Roman", Times, serif;
        font-size: 10pt;
    }
}

/* Base Font Settings */
body {
    font-family: "Times New Roman", Times, serif; /* Rule b */
    font-size: 12pt;       /* Rule b */
    line-height: 2;        /* Rule g: Double Space */
    text-align: justify;   /* Rule f */
    margin: 0;
}

/* Headings */
h1.chapter-name {
    font-size: 14pt;                   /* Rule e */
    text-transform: uppercase;         /* Rule e */
    font-weight: bold;
    text-align: center;
    page-break-before: always;         /* Start chapters on new page */
    margin-top: 0;
    padding-top: 0;
}

h2.section-heading {
    font-size: 12pt;                   /* Rule d */
    text-transform: uppercase;         /* Rule d */
    font-weight: bold;
    margin-top: 24pt;
    margin-bottom: 12pt;
    page-break-after: avoid;           /* Keep heading with text */
}

h3.subsection-heading {
    font-size: 12pt;                   /* Rule c */
    text-transform: none;              /* Rule c: Normal casing */
    font-weight: bold;
    margin-top: 18pt;
    margin-bottom: 12pt;
    page-break-after: avoid;
}

/* Paragraphs */
p {
    margin-bottom: 12pt;
    text-indent: 0; /* Modern style, or keep 1cm if preferred, but user just said 'Justified'. Standard reports usually indent or use spacing. */
}

/* Tables */
table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12pt;
    margin-bottom: 12pt;
}
th, td {
    border: 1px solid black;
    padding: 6pt;
    vertical-align: top;
    line-height: 1.3; /* Single space inside tables looks better */
}

/* Mermaid / Images */
.mermaid {
    display: flex;
    justify-content: center;
    margin: 24pt 0;
    width: 100%;
}
.diagram-container {
    text-align: center;
    margin: 1cm 0;
}
.diagram-caption {
    font-weight: bold;
    font-size: 11pt;
    margin-top: 6pt;
}

/* Helper for page breaks */
.page-break {
    page-break-before: always;
}
"""

# ----------------------------------------------------
# 3. MERGE CONTENT
# ----------------------------------------------------
full_html_content = ""

for i, filename in enumerate(files):
    path = os.path.join(base_dir, filename)
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Extract body only
            match = re.search(r'<body[^>]*>(.*?)</body>', content, re.DOTALL)
            if match:
                body_inner = match.group(1)
                
                # Check for "Chapter 5" which has Mermaid.js
                # Weasyprint can't execute JS. We'll replace mermaid div with a placeholder text note
                # because we can't render JS diagrams in Python without a browser.
                if "mermaid" in body_inner:
                     body_inner = body_inner.replace('<div class="mermaid">', '<div class="diagram-placehoder" style="border:1px dashed #000; padding:20px; text-align:center;"><strong>[Diagrams generated by JS - Please See HTML Version for Visuals]</strong><br><pre>')
                     body_inner = body_inner.replace('</div>', '</pre></div>', 1) 
                     # Note: This is a hack because WeasyPrint is static. 
                     # Perfect PDF requires Browser Print. We will prioritize the HTML output for the user to print.
                
                # Force Page Break for every new file (except the first)
                # But h1.chapter-name has page-break-before: always; so we are good for chapters.
                # Title page doesn't need break before.
                
                full_html_content += f'<div class="section-wrapper">{body_inner}</div>'

# ----------------------------------------------------
# 4. GENERATE PDF
# ----------------------------------------------------
final_html_str = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>{css_string}</style>
</head>
<body>
{full_html_content}
</body>
</html>
"""

# Create PDF
print("Generating PDF with WeasyPrint...")
HTML(string=final_html_str).write_pdf(output_pdf)
print(f"PDF Generated: {output_pdf}")
